# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7ad91ca3f4010d444e5367c4aa09bacc75d4faeb4528824d581c389725bf6fa9e8d20fd56d152fb07d2e62b39a32fc55bee8b81e0039bb8e1e5147195db7168

test:
  secret_key_base: 9c0c4549bd4c611cfe1d6232dbe17e34a39d5c70e767ee8ba0a4799c99a5bee2095af23290b003f27f54452d08a66765a36f6716d730e1e69a43742da13eb43a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
